## Choose the branch to deploy in aws beanstalk // repo: https://github.com/marketplace/actions/beanstalk-deploy
name: Deploy dev branch on aws beanstalk
on:
  #push:
  #  branches:
  #  - dev
  workflow_dispatch:
    inputs:
      name:
        description: 'Insert the version of the deploy'
        required: true
        default: 'Manual trigger to EB - default name - 0.1'
      home:
        description: 'location'
        required: false
        default: 'My location'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - run: |
        echo "Hello, this is the number of the build: # ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
    
    ## Checkout of the repo using "dev" branch // repo: https://github.com/marketplace/actions/checkout
    - name: Checkout source php code
      uses: actions/checkout@v2
      with:
        ref: s2021-s26
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."

    ## Need to check how to do 
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    ## Deploy to aws EB 
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: app-university
        environment_name: app-university-env
        version_label: 1
        region: us-east-1
        deployment_package: deploy.zip
